
title: ChronosLights – Portable Table Lamps
description: Cordless rechargeable table lamps for interior designers, home decor, restaurants, cafes and architects. No wires, no mess – just style.
author: ChronosLights
theme: minima
markdown: kramdown
